### ISSUE TITLE
cannot find package "github.com/skroutz/mistry/cmd/mistryd/statik"

### ISSUE THREAD

**Issue by jason-rutherford** [skroutz/mistry#123]
I'm interesting in trying mistry. Thanks for sharing. I'm not familiar with go but when I try to `go get -u github.com/skroutz/mistry/cmd/mistryd` or go build mistryd I get this error:

```
cannot find package "github.com/skroutz/mistry/cmd/mistryd/statik" in any of:
	/usr/local/opt/go/libexec/src/github.com/skroutz/mistry/cmd/mistryd/statik (from $GOROOT)
	/Users/jrutherford/golang/src/github.com/skroutz/mistry/cmd/mistryd/statik (from $GOPATH)
```

Am I missing something?

**Comment by agis** [comment]
`statik` is a build-time dependency, so it needs to be installed first:

```shell
$ go get github.com/rakyll/statik
```

That should do it.

P.S. we should probably mention this in the README.

**Comment by agis** [comment]
@jason-rutherford I'm going to go ahead and close this. Feel free to comment in this issue or re-open a new one if it's not resolved by my suggestion.
