### ISSUE TITLE
Global limit for concurrent builds

### ISSUE THREAD

**Issue by agis** [skroutz/mistry#68]
This could be a configuration option in the json.

**Comment by apostergiou** [comment]
The [existing configuration option](https://github.com/skroutz/mistry/blob/master/cmd/mistryd/config.sample.json#L7) is a global limit. 

Should we resolve this issue?

**Comment by agis** [comment]
Good catch. This has been done in https://github.com/skroutz/mistry/commit/73c44ecc924260ccf61bad220eb26cd51a1f30d6#diff-557f6db93cde47890e9a8c960c8fc481.
