### ISSUE TITLE
Support for opaque build parameters

### ISSUE THREAD

**Issue by agis** [skroutz/mistry#96]
Currently, every build parameter is taken into account when computing a job's ID and therefore has impact on result caching.

There are times, however, when one wants to submit totally opaque parameters (ie. that do not affect caching) for debugging or to provide additional context. In other words, some parameters are not significant as far as the build result is concerned, but still needs to be around.

For example, in a Rails application, currently one might do this:

```shell
$ mistry build --project rails-assets -- --commit-sha1=abced1
```

If someone wants to know if a mistry job on that project was for deployment and not for staging, one could do:

```shell
$ mistry build --project rails-assets -- --commit-sha1=abced1 --environment=staging
```

But this would result in the 2nd job being completely different from the 1st one, even though the artifacts are the exact same in both occasions. The rails environment that this is being deployed to doesn't affect the artifacts, it's there only to provide some context for when debugging.

So what we need, is a way to tell mistry that some parameters are there only for debugging, and do not affect the build results.

**Comment by ctrochalakis** [comment]
This can be really useful.

> So what we need, is a way to tell mistry that some parameters are there only for debugging, and do not affect the build results.

What about prefixing those parameters with a dot (.environment) or an underscore (_environment)?

**Comment by agis** [comment]
The `_` sounds good to me.
